In [1]:
# %pip install pandas numpy

Collecting pandas
  Downloading pandas-3.0.0-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.4.1-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gujin\dev\j-notebook\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\gujin\dev\j-notebook\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\gujin\dev\j-notebook\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.9 MB 12.6 MB/s eta 0:00:01
   ---------------------- ----------------- 5.5/9.9 MB 18.8 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 20.3 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 18.9 MB/s  0:00:00
Downloading numpy-2.4.1-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ------------- -------------------------- 4.2/12.4 MB 23.6 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.4 MB 18.8 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.4 MB 19.1 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 18.1 MB/s  0:00:00
Installing collected packages: numpy, pandas

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]

In [3]:
import pandas as pd
import numpy as np

In [4]:
pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 120)

In [5]:
print("✅ Ready — pandas:", pd.__version__, "| numpy:", np.__version__)

✅ Ready — pandas: 3.0.0 | numpy: 2.4.1

In [1]:
import sys, site, os, platform
from pathlib import Path

print("Python executable:", sys.executable)
print("Python version   :", platform.python_version())
print("Platform         :", platform.platform())
print("Site-packages    :", site.getsitepackages() if hasattr(site, "getsitepackages") else site.getusersitepackages())

Python executable: c:\Users\gujin\Dev\J-Notebook\venv\Scripts\python.exe
Python version   : 3.14.2
Platform         : Windows-11-10.0.26100-SP0
Site-packages    : ['c:\\Users\\gujin\\Dev\\J-Notebook\\venv', 'c:\\Users\\gujin\\Dev\\J-Notebook\\venv\\Lib\\site-packages']

# Transforming DataFrames
## Inspecting
basic operations: head(), info(), describe(), shape, columns,

In [6]:
# Read the CSV file into a DataFrame
csv_path = 'dummy_data.csv'
df_csv = pd.read_csv(csv_path)

# Display the DataFrame
display(df_csv)

# Inspecting the DataFrame
print("\nHead:", df_csv.head()) # head(): Display the first few rows of the DataFrame
print("\nShape:", df_csv.shape) # shape: Get the number of rows and columns in the DataFrame
print("\nColumns:", df_csv.columns) # columns: Get the column names of the DataFrame
print("\nInfo:") 
display(df_csv.info()) # info(): Get a concise summary of the DataFrame, including data types and non-null counts
print("\nDescribe:")
display(df_csv.describe()) # describe(): Generate a few summary statistics for each column

       Name  Age           City  Occupation  Salary
0     Alice   30       New York    Engineer   70000
1       Bob   30         London      Doctor   90000
2   Charlie   35          Paris      Artist   50000
3     David   35         Berlin     Teacher   60000
4       Eva   22          Tokyo     Student       0
5     Frank   28         Sydney        Chef   55000
6     Grace   32  San Francisco    Designer   80000
7     Helen   27          Seoul   Scientist   75000
8       Ian   45        Toronto     Manager   95000
9     Julia   38      Singapore      Lawyer   85000
10    Kevin   30        Chicago     Analyst   65000
11    Linda   35    Los Angeles      Writer   52000
12     Mike   29       New York   Developer   72000
13     Nina   34       New York  Consultant   81000
14    Oscar   41       New York   Architect   95000

Head:       Name  Age      City Occupation  Salary
0    Alice   30  New York   Engineer   70000
1      Bob   30    London     Doctor   90000
2  Charlie   35     Paris     Artist   50000
3    David   35    Berlin    Teacher   60000
4      Eva   22     Tokyo    Student       0

Shape: (15, 5)

Columns: Index(['Name', 'Age', 'City', 'Occupation', 'Salary'], dtype='str')

Info:
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        15 non-null     str
 1   Age         15 non-null     int64
 2   City        15 non-null     str
 3   Occupation  15 non-null     str
 4   Salary      15 non-null     int64
dtypes: int64(2), str(3)
memory usage: 732.0 bytes

None

Describe:

             Age        Salary
count  15.000000     15.000000
mean   32.733333  68333.333333
std     5.799836  23990.077314
min    22.000000      0.000000
25%    29.500000  57500.000000
50%    32.000000  72000.000000
75%    35.000000  83000.000000
max    45.000000  95000.000000

print() vs display()

- print() shows text output in the notebook’s output area, just like in a terminal. It’s good for simple text, numbers, or debugging.
- display() is a special function (from IPython) that shows rich objects—like DataFrames, plots, or HTML—in a nicely formatted way.

Use print() for plain text and display() for DataFrames or other rich objects to get a better visual result.

A pandas DataFrame consists of three main components:

- values: The actual data stored in a 2D array (rows and columns).
- columns: The labels for each column (like headers in a table).
- index: The labels for each row (like row numbers or custom labels).

In [37]:
print(df_csv.values) # values: Get the underlying numpy array of the DataFrame
print(df_csv.columns) # columns: Get the column names of the DataFrame
print(df_csv.dtypes) # dtypes: Get the data types of each column in the DataFrame
print(df_csv.index) # index: Get the index (row labels) of the DataFrame

[['Alice' 30 'New York' 'Engineer' 70000]
 ['Bob' 30 'London' 'Doctor' 90000]
 ['Charlie' 35 'Paris' 'Artist' 50000]
 ['David' 35 'Berlin' 'Teacher' 60000]
 ['Eva' 22 'Tokyo' 'Student' 0]
 ['Frank' 28 'Sydney' 'Chef' 55000]
 ['Grace' 32 'San Francisco' 'Designer' 80000]
 ['Helen' 27 'Seoul' 'Scientist' 75000]
 ['Ian' 45 'Toronto' 'Manager' 95000]
 ['Julia' 38 'Singapore' 'Lawyer' 85000]
 ['Kevin' 30 'Chicago' 'Analyst' 65000]
 ['Linda' 35 'Los Angeles' 'Writer' 52000]]
Index(['Name', 'Age', 'City', 'Occupation', 'Salary'], dtype='str')
Name            str
Age           int64
City            str
Occupation      str
Salary        int64
dtype: object
RangeIndex(start=0, stop=12, step=1)

## Sorting
Sorting in a DataFrame means rearranging the rows based on the values in one or more columns or by the index.
sort_values('column_name'): Sort the DataFrame by the specified column(s)

In [38]:
df_csv.sort_values("Age", ascending=True) # sort_values(): Sort the DataFrame by Age column in ascending order

       Name  Age           City Occupation  Salary
4       Eva   22          Tokyo    Student       0
7     Helen   27          Seoul  Scientist   75000
5     Frank   28         Sydney       Chef   55000
0     Alice   30       New York   Engineer   70000
1       Bob   30         London     Doctor   90000
10    Kevin   30        Chicago    Analyst   65000
6     Grace   32  San Francisco   Designer   80000
3     David   35         Berlin    Teacher   60000
2   Charlie   35          Paris     Artist   50000
11    Linda   35    Los Angeles     Writer   52000
9     Julia   38      Singapore     Lawyer   85000
8       Ian   45        Toronto    Manager   95000

In [39]:
df_csv.sort_values(["Age", "Salary"], ascending=[True, False]) # sort_values(): Sort the DataFrame by Age column in ascending order and Salary column in descending order

       Name  Age           City Occupation  Salary
4       Eva   22          Tokyo    Student       0
7     Helen   27          Seoul  Scientist   75000
5     Frank   28         Sydney       Chef   55000
1       Bob   30         London     Doctor   90000
0     Alice   30       New York   Engineer   70000
10    Kevin   30        Chicago    Analyst   65000
6     Grace   32  San Francisco   Designer   80000
3     David   35         Berlin    Teacher   60000
11    Linda   35    Los Angeles     Writer   52000
2   Charlie   35          Paris     Artist   50000
9     Julia   38      Singapore     Lawyer   85000
8       Ian   45        Toronto    Manager   95000

By combining .sort_values() with .head(), you can answer questions in the form, "What are the top cases where…?".


## Subsetting
### Subsetting columns
Subset columns in a DataFrame means selecting only specific columns from the whole table, instead of using all columns.
You can do this by passing a list of column names to the DataFrame, like df[['Age', 'Salary']]. This returns a new DataFrame with just those columns.

In [ ]:
df_csv[["Name", "City"]] # Select only the Name and City columns from the DataFrame
# external [] is used to select columns by name, and the inner [] is used to specify a list of column names to select. It is equivalent to:
# cols_to_subset = ["Name", "City"]
# df_csv[cols_to_subset]

       Name           City
0     Alice       New York
1       Bob         London
2   Charlie          Paris
3     David         Berlin
4       Eva          Tokyo
5     Frank         Sydney
6     Grace  San Francisco
7     Helen          Seoul
8       Ian        Toronto
9     Julia      Singapore
10    Kevin        Chicago
11    Linda    Los Angeles

### Subsetting rows
A large part of data science is about finding which bits of your dataset are interesting. One of the simplest techniques for this is to find a subset of rows that match some criteria. This is sometimes known as filtering rows or selecting rows.

The most common way to subset rows is to use boolean indexing (relational operators to return True or False for each row, then pass that inside square brackets).

In [41]:
df_csv[df_csv["Age"] > 30] # Subset by selecting rows where the Age column is greater than 30

       Name  Age           City Occupation  Salary
2   Charlie   35          Paris     Artist   50000
3     David   35         Berlin    Teacher   60000
6     Grace   32  San Francisco   Designer   80000
8       Ian   45        Toronto    Manager   95000
9     Julia   38      Singapore     Lawyer   85000
11    Linda   35    Los Angeles     Writer   52000

In [45]:
df_csv[df_csv["City"] == "New York"] # Subset by selecting rows where the City column is equal to "New York"

     Name  Age      City  Occupation  Salary
0   Alice   30  New York    Engineer   70000
12   Mike   29  New York   Developer   72000
13   Nina   34  New York  Consultant   81000
14  Oscar   41  New York   Architect   95000

In [46]:
# Subset by several conditions
is_older_than_30 = df_csv["Age"] > 30
is_from_new_york = df_csv["City"] == "New York"
df_csv[is_older_than_30 & is_from_new_york] # Subset by selecting rows where both conditions are True

     Name  Age      City  Occupation  Salary
13   Nina   34  New York  Consultant   81000
14  Oscar   41  New York   Architect   95000

In [47]:
# Subset using isin operator
cities_to_include = ["New York", "Los Angeles"]
df_csv[df_csv["City"].isin(cities_to_include)] # Subset by selecting rows where the City column is in the list of cities_to_include

     Name  Age         City  Occupation  Salary
0   Alice   30     New York    Engineer   70000
11  Linda   35  Los Angeles      Writer   52000
12   Mike   29     New York   Developer   72000
13   Nina   34     New York  Consultant   81000
14  Oscar   41     New York   Architect   95000

In [48]:
# Example: Subsetting rows for high earners in New York
subset_high_earners_ny = df_csv[(df_csv['City'] == 'New York') & (df_csv['Salary'] > 80000)]
display(subset_high_earners_ny)

     Name  Age      City  Occupation  Salary
13   Nina   34  New York  Consultant   81000
14  Oscar   41  New York   Architect   95000

In [ ]:
# Example: Subsetting rows for scientists or designers with salary below 80000
subset_profession_salary = df_csv[(df_csv['Occupation'].isin(['Scientist', 'Designer'])) & (df_csv['Salary'] < 80000)]
display(subset_profession_salary)

    Name  Age   City Occupation  Salary
7  Helen   27  Seoul  Scientist   75000

## Adding new columns
You can create new columns from scratch by simply assigning a new column name and values to the DataFrame, like df['NewColumn'] = values, but it is also common to derive them from other columns, for example, by adding columns together or by changing their units.

In [51]:
# Derive new columns from other columns
df_csv['Tax'] = df_csv['Salary'] * 0.1  # Tax is 10% of Salary
df_csv['NetSalary'] = df_csv['Salary'] - df_csv['Tax']  # Net salary after tax
display(df_csv[['Name', 'Salary', 'Tax', 'NetSalary']])

       Name  Salary     Tax  NetSalary
0     Alice   70000  7000.0    63000.0
1       Bob   90000  9000.0    81000.0
2   Charlie   50000  5000.0    45000.0
3     David   60000  6000.0    54000.0
4       Eva       0     0.0        0.0
5     Frank   55000  5500.0    49500.0
6     Grace   80000  8000.0    72000.0
7     Helen   75000  7500.0    67500.0
8       Ian   95000  9500.0    85500.0
9     Julia   85000  8500.0    76500.0
10    Kevin   65000  6500.0    58500.0
11    Linda   52000  5200.0    46800.0
12     Mike   72000  7200.0    64800.0
13     Nina   81000  8100.0    72900.0
14    Oscar   95000  9500.0    85500.0

In [ ]:
# Combo question: Who are the top 3 highest net earners in New York, after tax?
df_csv['Tax'] = df_csv['Salary'] * 0.1
df_csv['NetSalary'] = df_csv['Salary'] - df_csv['Tax']
subset_ny = df_csv[df_csv['City'] == 'New York']
top_net_earners_ny = subset_ny.sort_values('NetSalary', ascending=False).head(3)
display(top_net_earners_ny[['Name', 'Salary', 'Tax', 'NetSalary']])

     Name  Salary     Tax  NetSalary
14  Oscar   95000  9500.0    85500.0
13   Nina   81000  8100.0    72900.0
12   Mike   72000  7200.0    64800.0