In [1]:
# %pip install pandas numpy

Collecting pandas
  Downloading pandas-3.0.0-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.4.1-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gujin\dev\j-notebook\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\gujin\dev\j-notebook\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\gujin\dev\j-notebook\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.9 MB 12.6 MB/s eta 0:00:01
   ---------------------- ----------------- 5.5/9.9 MB 18.8 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 20.3 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 18.9 MB/s  0:00:00
Downloading numpy-2.4.1-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ------------- -------------------------- 4.2/12.4 MB 23.6 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.4 MB 18.8 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.4 MB 19.1 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 18.1 MB/s  0:00:00
Installing collected packages: numpy, pandas

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]

In [3]:
import pandas as pd
import numpy as np

In [4]:
pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 120)

In [5]:
print("✅ Ready — pandas:", pd.__version__, "| numpy:", np.__version__)

✅ Ready — pandas: 3.0.0 | numpy: 2.4.1

In [1]:
import sys, site, os, platform
from pathlib import Path

print("Python executable:", sys.executable)
print("Python version   :", platform.python_version())
print("Platform         :", platform.platform())
print("Site-packages    :", site.getsitepackages() if hasattr(site, "getsitepackages") else site.getusersitepackages())

Python executable: c:\Users\gujin\Dev\J-Notebook\venv\Scripts\python.exe
Python version   : 3.14.2
Platform         : Windows-11-10.0.26100-SP0
Site-packages    : ['c:\\Users\\gujin\\Dev\\J-Notebook\\venv', 'c:\\Users\\gujin\\Dev\\J-Notebook\\venv\\Lib\\site-packages']

# Transforming DataFrames
## Inspecting
basic operations: head(), info(), describe(), shape, columns,

In [10]:
# Read the CSV file into a DataFrame
csv_path = 'dummy_data.csv'
df_csv = pd.read_csv(csv_path)

# Display the DataFrame
display(df_csv)

# Inspecting the DataFrame
print("\nHead:", df_csv.head()) # head(): Display the first few rows of the DataFrame
print("\nShape:", df_csv.shape) # shape: Get the number of rows and columns in the DataFrame
print("\nColumns:", df_csv.columns) # columns: Get the column names of the DataFrame
print("\nInfo:") 
display(df_csv.info()) # info(): Get a concise summary of the DataFrame, including data types and non-null counts
print("\nDescribe:")
display(df_csv.describe()) # describe(): Generate a few summary statistics for each column

       Name  Age           City  Occupation  Salary
0     Alice   30       New York    Engineer   70000
1       Bob   30         London      Doctor   90000
2   Charlie   35          Paris      Artist   50000
3     David   35         Berlin     Teacher   60000
4       Eva   22          Tokyo     Student   15000
5     Frank   28         Sydney        Chef   55000
6     Grace   32  San Francisco    Designer   80000
7     Helen   27          Seoul   Scientist   75000
8       Ian   45        Toronto     Manager   95000
9     Julia   38      Singapore      Lawyer   85000
10    Kevin   30        Chicago     Analyst   65000
11    Linda   35    Los Angeles      Writer   52000
12     Mike   29       New York   Developer   72000
13     Nina   34       New York  Consultant   81000
14    Oscar   41       New York   Architect   95000
15     Paul   26         London     Student   12000
16    Quinn   33         London    Engineer   85000
17   Rachel   40         London     Manager  102000
18      Sam   28  San Francisco   Developer   95000
19     Tina   31  San Francisco    Designer   88000
20      Uma   36  San Francisco    Engineer  110000
21   Victor   29        Chicago     Analyst   67000
22    Wendy   44        Chicago     Manager   98000
23   Xander   27        Chicago   Developer   69000
24     Yara   32    Los Angeles    Designer   76000
25      Zoe   38    Los Angeles      Lawyer   91000
26    Aaron   25    Los Angeles     Student   14000
27    Bella   43       New York      Doctor  120000
28   Carlos   37       New York      Lawyer  105000
29    Diana   29       New York     Analyst   68000
30    Ethan   34         London      Doctor   98000
31    Fiona   26         London     Analyst   58000
32   George   48          Paris   Architect   82000
33   Hannah   31          Paris    Designer   65000
34     Ivan   23          Paris     Student   11000
35     Jade   39         Berlin    Engineer   78000
36     Karl   33         Berlin      Doctor   94000
37     Lena   27         Berlin     Teacher   55000
38    Marco   45          Tokyo     Manager   88000
39     Nora   30          Tokyo    Engineer   79000
40   Oliver   28          Tokyo   Developer   74000
41    Priya   35         Sydney   Scientist   81000
42     Rick   41         Sydney      Doctor   99000
43     Sara   26         Sydney     Teacher   53000
44      Tom   38        Toronto      Lawyer   97000
45   Ursula   32        Toronto    Engineer   84000
46     Vera   29        Toronto     Analyst   66000
47     Will   44      Singapore     Manager  115000
48     Xena   36      Singapore    Engineer  105000
49    Yusuf   31      Singapore   Developer   89000

Head:       Name  Age      City Occupation  Salary
0    Alice   30  New York   Engineer   70000
1      Bob   30    London     Doctor   90000
2  Charlie   35     Paris     Artist   50000
3    David   35    Berlin    Teacher   60000
4      Eva   22     Tokyo    Student   15000

Shape: (50, 5)

Columns: Index(['Name', 'Age', 'City', 'Occupation', 'Salary'], dtype='str')

Info:
<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        50 non-null     str
 1   Age         50 non-null     int64
 2   City        50 non-null     str
 3   Occupation  50 non-null     str
 4   Salary      50 non-null     int64
dtypes: int64(2), str(3)
memory usage: 2.1 KB

None

Describe:

             Age         Salary
count  50.000000      50.000000
mean   33.300000   76220.000000
std     6.260501   25255.664145
min    22.000000   11000.000000
25%    29.000000   65250.000000
50%    32.000000   80500.000000
75%    37.750000   94750.000000
max    48.000000  120000.000000

print() vs display()

- print() shows text output in the notebook’s output area, just like in a terminal. It’s good for simple text, numbers, or debugging.
- display() is a special function (from IPython) that shows rich objects—like DataFrames, plots, or HTML—in a nicely formatted way.

Use print() for plain text and display() for DataFrames or other rich objects to get a better visual result.

A pandas DataFrame consists of three main components:

- values: The actual data stored in a 2D array (rows and columns).
- columns: The labels for each column (like headers in a table).
- index: The labels for each row (like row numbers or custom labels).

In [37]:
print(df_csv.values) # values: Get the underlying numpy array of the DataFrame
print(df_csv.columns) # columns: Get the column names of the DataFrame
print(df_csv.dtypes) # dtypes: Get the data types of each column in the DataFrame
print(df_csv.index) # index: Get the index (row labels) of the DataFrame

[['Alice' 30 'New York' 'Engineer' 70000]
 ['Bob' 30 'London' 'Doctor' 90000]
 ['Charlie' 35 'Paris' 'Artist' 50000]
 ['David' 35 'Berlin' 'Teacher' 60000]
 ['Eva' 22 'Tokyo' 'Student' 0]
 ['Frank' 28 'Sydney' 'Chef' 55000]
 ['Grace' 32 'San Francisco' 'Designer' 80000]
 ['Helen' 27 'Seoul' 'Scientist' 75000]
 ['Ian' 45 'Toronto' 'Manager' 95000]
 ['Julia' 38 'Singapore' 'Lawyer' 85000]
 ['Kevin' 30 'Chicago' 'Analyst' 65000]
 ['Linda' 35 'Los Angeles' 'Writer' 52000]]
Index(['Name', 'Age', 'City', 'Occupation', 'Salary'], dtype='str')
Name            str
Age           int64
City            str
Occupation      str
Salary        int64
dtype: object
RangeIndex(start=0, stop=12, step=1)

## Sorting
Sorting in a DataFrame means rearranging the rows based on the values in one or more columns or by the index.
sort_values('column_name'): Sort the DataFrame by the specified column(s)

In [38]:
df_csv.sort_values("Age", ascending=True) # sort_values(): Sort the DataFrame by Age column in ascending order

       Name  Age           City Occupation  Salary
4       Eva   22          Tokyo    Student       0
7     Helen   27          Seoul  Scientist   75000
5     Frank   28         Sydney       Chef   55000
0     Alice   30       New York   Engineer   70000
1       Bob   30         London     Doctor   90000
10    Kevin   30        Chicago    Analyst   65000
6     Grace   32  San Francisco   Designer   80000
3     David   35         Berlin    Teacher   60000
2   Charlie   35          Paris     Artist   50000
11    Linda   35    Los Angeles     Writer   52000
9     Julia   38      Singapore     Lawyer   85000
8       Ian   45        Toronto    Manager   95000

In [39]:
df_csv.sort_values(["Age", "Salary"], ascending=[True, False]) # sort_values(): Sort the DataFrame by Age column in ascending order and Salary column in descending order

       Name  Age           City Occupation  Salary
4       Eva   22          Tokyo    Student       0
7     Helen   27          Seoul  Scientist   75000
5     Frank   28         Sydney       Chef   55000
1       Bob   30         London     Doctor   90000
0     Alice   30       New York   Engineer   70000
10    Kevin   30        Chicago    Analyst   65000
6     Grace   32  San Francisco   Designer   80000
3     David   35         Berlin    Teacher   60000
11    Linda   35    Los Angeles     Writer   52000
2   Charlie   35          Paris     Artist   50000
9     Julia   38      Singapore     Lawyer   85000
8       Ian   45        Toronto    Manager   95000

By combining .sort_values() with .head(), you can answer questions in the form, "What are the top cases where…?".


## Subsetting
### Subsetting columns
Subset columns in a DataFrame means selecting only specific columns from the whole table, instead of using all columns.
You can do this by passing a list of column names to the DataFrame, like df[['Age', 'Salary']]. This returns a new DataFrame with just those columns.

In [ ]:
df_csv[["Name", "City"]] # Select only the Name and City columns from the DataFrame
# external [] is used to select columns by name, and the inner [] is used to specify a list of column names to select. It is equivalent to:
# cols_to_subset = ["Name", "City"]
# df_csv[cols_to_subset]

       Name           City
0     Alice       New York
1       Bob         London
2   Charlie          Paris
3     David         Berlin
4       Eva          Tokyo
5     Frank         Sydney
6     Grace  San Francisco
7     Helen          Seoul
8       Ian        Toronto
9     Julia      Singapore
10    Kevin        Chicago
11    Linda    Los Angeles

### Subsetting rows
A large part of data science is about finding which bits of your dataset are interesting. One of the simplest techniques for this is to find a subset of rows that match some criteria. This is sometimes known as filtering rows or selecting rows.

The most common way to subset rows is to use boolean indexing (relational operators to return True or False for each row, then pass that inside square brackets).

In [41]:
df_csv[df_csv["Age"] > 30] # Subset by selecting rows where the Age column is greater than 30

       Name  Age           City Occupation  Salary
2   Charlie   35          Paris     Artist   50000
3     David   35         Berlin    Teacher   60000
6     Grace   32  San Francisco   Designer   80000
8       Ian   45        Toronto    Manager   95000
9     Julia   38      Singapore     Lawyer   85000
11    Linda   35    Los Angeles     Writer   52000

In [45]:
df_csv[df_csv["City"] == "New York"] # Subset by selecting rows where the City column is equal to "New York"

     Name  Age      City  Occupation  Salary
0   Alice   30  New York    Engineer   70000
12   Mike   29  New York   Developer   72000
13   Nina   34  New York  Consultant   81000
14  Oscar   41  New York   Architect   95000

In [46]:
# Subset by several conditions
is_older_than_30 = df_csv["Age"] > 30
is_from_new_york = df_csv["City"] == "New York"
df_csv[is_older_than_30 & is_from_new_york] # Subset by selecting rows where both conditions are True

     Name  Age      City  Occupation  Salary
13   Nina   34  New York  Consultant   81000
14  Oscar   41  New York   Architect   95000

In [47]:
# Subset using isin operator
cities_to_include = ["New York", "Los Angeles"]
df_csv[df_csv["City"].isin(cities_to_include)] # Subset by selecting rows where the City column is in the list of cities_to_include

     Name  Age         City  Occupation  Salary
0   Alice   30     New York    Engineer   70000
11  Linda   35  Los Angeles      Writer   52000
12   Mike   29     New York   Developer   72000
13   Nina   34     New York  Consultant   81000
14  Oscar   41     New York   Architect   95000

In [48]:
# Example: Subsetting rows for high earners in New York
subset_high_earners_ny = df_csv[(df_csv['City'] == 'New York') & (df_csv['Salary'] > 80000)]
display(subset_high_earners_ny)

     Name  Age      City  Occupation  Salary
13   Nina   34  New York  Consultant   81000
14  Oscar   41  New York   Architect   95000

In [ ]:
# Example: Subsetting rows for scientists or designers with salary below 80000
subset_profession_salary = df_csv[(df_csv['Occupation'].isin(['Scientist', 'Designer'])) & (df_csv['Salary'] < 80000)]
display(subset_profession_salary)

    Name  Age   City Occupation  Salary
7  Helen   27  Seoul  Scientist   75000

## Adding new columns
You can create new columns from scratch by simply assigning a new column name and values to the DataFrame, like df['NewColumn'] = values, but it is also common to derive them from other columns, for example, by adding columns together or by changing their units.

In [51]:
# Derive new columns from other columns
df_csv['Tax'] = df_csv['Salary'] * 0.1  # Tax is 10% of Salary
df_csv['NetSalary'] = df_csv['Salary'] - df_csv['Tax']  # Net salary after tax
display(df_csv[['Name', 'Salary', 'Tax', 'NetSalary']])

       Name  Salary     Tax  NetSalary
0     Alice   70000  7000.0    63000.0
1       Bob   90000  9000.0    81000.0
2   Charlie   50000  5000.0    45000.0
3     David   60000  6000.0    54000.0
4       Eva       0     0.0        0.0
5     Frank   55000  5500.0    49500.0
6     Grace   80000  8000.0    72000.0
7     Helen   75000  7500.0    67500.0
8       Ian   95000  9500.0    85500.0
9     Julia   85000  8500.0    76500.0
10    Kevin   65000  6500.0    58500.0
11    Linda   52000  5200.0    46800.0
12     Mike   72000  7200.0    64800.0
13     Nina   81000  8100.0    72900.0
14    Oscar   95000  9500.0    85500.0

In [ ]:
# Combo question: Who are the top 3 highest net earners in New York, after tax?
df_csv['Tax'] = df_csv['Salary'] * 0.1
df_csv['NetSalary'] = df_csv['Salary'] - df_csv['Tax']
subset_ny = df_csv[df_csv['City'] == 'New York']
top_net_earners_ny = subset_ny.sort_values('NetSalary', ascending=False).head(3)
display(top_net_earners_ny[['Name', 'Salary', 'Tax', 'NetSalary']])

     Name  Salary     Tax  NetSalary
14  Oscar   95000  9500.0    85500.0
13   Nina   81000  8100.0    72900.0
12   Mike   72000  7200.0    64800.0

# Aggregating DataFrames
Aggregating data means computing **summary statistics** across groups of rows, collapsing many rows down into a single value (or one row per group).

## Summary statistics
Calculating summary statistics (summarize many numbers in one statistic) allows you to get a better sense of your data, even if there's a lot of it.

Common summary functions: mean(), sum(), count(), min(), max(), median(), std()

Core Concept: groupby()

The most common pattern is split → apply → combine:

1. Split the data into groups based on a column
2. Apply an aggregation function (sum, mean, count, etc.)
3. Combine the results into a new DataFrame

In [12]:
df_csv.groupby('City')['Salary'].mean() # Group by City and calculate the mean Salary for each city

City
Berlin           71750.000000
Chicago          74750.000000
London           74166.666667
Los Angeles      58250.000000
New York         87285.714286
Paris            52000.000000
San Francisco    93250.000000
Seoul            75000.000000
Singapore        98500.000000
Sydney           72000.000000
Tokyo            64000.000000
Toronto          85500.000000
Name: Salary, dtype: float64

### Efficient summaries .agg()
The .agg() method allows you to apply your own custom functions to a DataFrame, as well as apply functions to more than one column of a DataFrame at once, making your aggregations super-efficient.

In [13]:
# Multiple Aggregations with .agg()

df_csv.groupby("City")["Salary"].agg(["mean", "min", "max"]) # Group by City and calculate the mean, min, and max Salary for each city

                       mean    min     max
City
Berlin         71750.000000  55000   94000
Chicago        74750.000000  65000   98000
London         74166.666667  12000  102000
Los Angeles    58250.000000  14000   91000
New York       87285.714286  68000  120000
Paris          52000.000000  11000   82000
San Francisco  93250.000000  80000  110000
Seoul          75000.000000  75000   75000
Singapore      98500.000000  85000  115000
Sydney         72000.000000  53000   99000
Tokyo          64000.000000  15000   88000
Toronto        85500.000000  66000   97000

In [14]:
# Grouping by Multiple Columns, and Multiple Aggregations

df_csv.groupby(["City", "Occupation"])["Salary"].agg(["mean", "min", "max"]) # Group by City and Occupation, and calculate the mean, min, and max Salary for each group

                              mean     min     max
City          Occupation
Berlin        Doctor       94000.0   94000   94000
              Engineer     78000.0   78000   78000
              Teacher      57500.0   55000   60000
Chicago       Analyst      66000.0   65000   67000
              Developer    69000.0   69000   69000
              Manager      98000.0   98000   98000
London        Analyst      58000.0   58000   58000
              Doctor       94000.0   90000   98000
              Engineer     85000.0   85000   85000
              Manager     102000.0  102000  102000
              Student      12000.0   12000   12000
Los Angeles   Designer     76000.0   76000   76000
              Lawyer       91000.0   91000   91000
              Student      14000.0   14000   14000
              Writer       52000.0   52000   52000
New York      Analyst      68000.0   68000   68000
              Architect    95000.0   95000   95000
              Consultant   81000.0   81000   81000
              Developer    72000.0   72000   72000
              Doctor      120000.0  120000  120000
              Engineer     70000.0   70000   70000
              Lawyer      105000.0  105000  105000
Paris         Architect    82000.0   82000   82000
              Artist       50000.0   50000   50000
              Designer     65000.0   65000   65000
              Student      11000.0   11000   11000
San Francisco Designer     84000.0   80000   88000
              Developer    95000.0   95000   95000
              Engineer    110000.0  110000  110000
Seoul         Scientist    75000.0   75000   75000
Singapore     Developer    89000.0   89000   89000
              Engineer    105000.0  105000  105000
              Lawyer       85000.0   85000   85000
              Manager     115000.0  115000  115000
Sydney        Chef         55000.0   55000   55000
              Doctor       99000.0   99000   99000
              Scientist    81000.0   81000   81000
              Teacher      53000.0   53000   53000
Tokyo         Developer    74000.0   74000   74000
              Engineer     79000.0   79000   79000
              Manager      88000.0   88000   88000
              Student      15000.0   15000   15000
Toronto       Analyst      66000.0   66000   66000
              Engineer     84000.0   84000   84000
              Lawyer       97000.0   97000   97000
              Manager      95000.0   95000   95000

## Cumulative Statistics
Cumulative statistics track a running value as you move through the rows — useful for spotting trends, running totals, and progressive highs/lows over time.

Common cumulative functions:
- cumsum(): running total
- cummax(): running highest value seen so far
- cummin(): running lowest value seen so far
- cumprod(): running product (less common in data science)

In [29]:
# cumsum() (e.g. payroll budget)
# Cumulative salary spend per city — sorted within each city group

df_sorted = df_csv.sort_values(["City", "Salary"]).reset_index(drop=True) # sort_values() and reset_index() after sorting
df_sorted["CumulativeSalary"] = df_sorted.groupby("City")["Salary"].cumsum() # cumsum(): Calculate the cumulative sum of the Salary column
display(df_sorted[["Name", "City", "Occupation", "Salary", "CumulativeSalary"]])

       Name           City  Occupation  Salary  CumulativeSalary
0      Lena         Berlin     Teacher   55000             55000
1     David         Berlin     Teacher   60000            115000
2      Jade         Berlin    Engineer   78000            193000
3      Karl         Berlin      Doctor   94000            287000
4     Kevin        Chicago     Analyst   65000             65000
5    Victor        Chicago     Analyst   67000            132000
6    Xander        Chicago   Developer   69000            201000
7     Wendy        Chicago     Manager   98000            299000
8      Paul         London     Student   12000             12000
9     Fiona         London     Analyst   58000             70000
10    Quinn         London    Engineer   85000            155000
11      Bob         London      Doctor   90000            245000
12    Ethan         London      Doctor   98000            343000
13   Rachel         London     Manager  102000            445000
14    Aaron    Los Angeles     Student   14000             14000
15    Linda    Los Angeles      Writer   52000             66000
16     Yara    Los Angeles    Designer   76000            142000
17      Zoe    Los Angeles      Lawyer   91000            233000
18    Diana       New York     Analyst   68000             68000
19    Alice       New York    Engineer   70000            138000
20     Mike       New York   Developer   72000            210000
21     Nina       New York  Consultant   81000            291000
22    Oscar       New York   Architect   95000            386000
23   Carlos       New York      Lawyer  105000            491000
24    Bella       New York      Doctor  120000            611000
25     Ivan          Paris     Student   11000             11000
26  Charlie          Paris      Artist   50000             61000
27   Hannah          Paris    Designer   65000            126000
28   George          Paris   Architect   82000            208000
29    Grace  San Francisco    Designer   80000             80000
30     Tina  San Francisco    Designer   88000            168000
31      Sam  San Francisco   Developer   95000            263000
32      Uma  San Francisco    Engineer  110000            373000
33    Helen          Seoul   Scientist   75000             75000
34    Julia      Singapore      Lawyer   85000             85000
35    Yusuf      Singapore   Developer   89000            174000
36     Xena      Singapore    Engineer  105000            279000
37     Will      Singapore     Manager  115000            394000
38     Sara         Sydney     Teacher   53000             53000
39    Frank         Sydney        Chef   55000            108000
40    Priya         Sydney   Scientist   81000            189000
41     Rick         Sydney      Doctor   99000            288000
42      Eva          Tokyo     Student   15000             15000
43   Oliver          Tokyo   Developer   74000             89000
44     Nora          Tokyo    Engineer   79000            168000
45    Marco          Tokyo     Manager   88000            256000
46     Vera        Toronto     Analyst   66000             66000
47   Ursula        Toronto    Engineer   84000            150000
48      Ian        Toronto     Manager   95000            245000
49      Tom        Toronto      Lawyer   97000            342000

## Summary vs cumulative statistics

They are parallel concepts, both under the broader umbrella of descriptive statistics.

```markdown
Descriptive Statistics
├── Summary Statistics       ← collapse many rows → one value
│     mean(), sum(), std()
│     groupby().agg()
│
└── Cumulative Statistics    ← transform rows → running value per row
      cumsum(), cummax(), cummin()
```

The key difference is the output shape:

```markdown
| Input      | Output | Question answered        |                                                        |
|------------|--------|--------------------------|--------------------------------------------------------|
| Summary    | N rows | 1 value (or 1 per group) | "What is the average salary in New York?"              |
| Cumulative | N rows | N rows (running value)   | "What is the total salary cost as we add each person?" |
```

In plain terms:

- Summary statistics reduce — they compress data into a single number. You lose the row-by-row detail.
- Cumulative statistics transform — they keep all rows but add a running calculation alongside. No data is lost.

## Counting
In pandas, "counting" means measuring how many rows exist — either in the whole DataFrame or per group. 

```markdown
| Method                   | What it counts                 |
|--------------------------|--------------------------------|
| len(df)                  | Total number of rows           |
| df["col"].count()        | Non-null values in a column    |
| df["col"].value_counts() | Frequency of each unique value |
| groupby().count()        | Rows per group                 |
```

In [32]:
# How many people are in the dataset?
len(df_csv) # len(): Get the number of rows in the DataFrame

50

In [33]:
# How many people per city?
df_csv.groupby('City')['Name'].count() # groupby() and count(): Group by City and count the number of names (people) in each city

City
Berlin           4
Chicago          4
London           6
Los Angeles      4
New York         7
Paris            4
San Francisco    4
Seoul            1
Singapore        4
Sydney           4
Tokyo            4
Toronto          4
Name: Name, dtype: int64

In [36]:
# How many per occupation? (value_counts is shorthand for Quick Frequency Count)
df_csv['Occupation'].value_counts() # value_counts(): Count the number of occurrences of each unique value in the Occupation column

Occupation
Engineer      7
Doctor        5
Manager       5
Analyst       5
Developer     5
Student       4
Designer      4
Lawyer        4
Teacher       3
Scientist     2
Architect     2
Artist        1
Chef          1
Writer        1
Consultant    1
Name: count, dtype: int64

In [37]:
# Count with proportion (normalize=True gives percentages)

df_csv["City"].value_counts(normalize=True) # value_counts(): Count the number of occurrences of each unique value in the City column

City
New York         0.14
London           0.12
Paris            0.08
Berlin           0.08
Tokyo            0.08
Sydney           0.08
San Francisco    0.08
Toronto          0.08
Singapore        0.08
Chicago          0.08
Los Angeles      0.08
Seoul            0.02
Name: proportion, dtype: float64

In [ ]:
# drop_duplicates()
# Removes duplicate rows. By default it keeps the first occurrence and drops the rest.

# Drop fully identical rows (rarely happen)
df_csv.drop_duplicates()

       Name  Age           City  Occupation  Salary
0     Alice   30       New York    Engineer   70000
1       Bob   30         London      Doctor   90000
2   Charlie   35          Paris      Artist   50000
3     David   35         Berlin     Teacher   60000
4       Eva   22          Tokyo     Student   15000
5     Frank   28         Sydney        Chef   55000
6     Grace   32  San Francisco    Designer   80000
7     Helen   27          Seoul   Scientist   75000
8       Ian   45        Toronto     Manager   95000
9     Julia   38      Singapore      Lawyer   85000
10    Kevin   30        Chicago     Analyst   65000
11    Linda   35    Los Angeles      Writer   52000
12     Mike   29       New York   Developer   72000
13     Nina   34       New York  Consultant   81000
14    Oscar   41       New York   Architect   95000
15     Paul   26         London     Student   12000
16    Quinn   33         London    Engineer   85000
17   Rachel   40         London     Manager  102000
18      Sam   28  San Francisco   Developer   95000
19     Tina   31  San Francisco    Designer   88000
20      Uma   36  San Francisco    Engineer  110000
21   Victor   29        Chicago     Analyst   67000
22    Wendy   44        Chicago     Manager   98000
23   Xander   27        Chicago   Developer   69000
24     Yara   32    Los Angeles    Designer   76000
25      Zoe   38    Los Angeles      Lawyer   91000
26    Aaron   25    Los Angeles     Student   14000
27    Bella   43       New York      Doctor  120000
28   Carlos   37       New York      Lawyer  105000
29    Diana   29       New York     Analyst   68000
30    Ethan   34         London      Doctor   98000
31    Fiona   26         London     Analyst   58000
32   George   48          Paris   Architect   82000
33   Hannah   31          Paris    Designer   65000
34     Ivan   23          Paris     Student   11000
35     Jade   39         Berlin    Engineer   78000
36     Karl   33         Berlin      Doctor   94000
37     Lena   27         Berlin     Teacher   55000
38    Marco   45          Tokyo     Manager   88000
39     Nora   30          Tokyo    Engineer   79000
40   Oliver   28          Tokyo   Developer   74000
41    Priya   35         Sydney   Scientist   81000
42     Rick   41         Sydney      Doctor   99000
43     Sara   26         Sydney     Teacher   53000
44      Tom   38        Toronto      Lawyer   97000
45   Ursula   32        Toronto    Engineer   84000
46     Vera   29        Toronto     Analyst   66000
47     Will   44      Singapore     Manager  115000
48     Xena   36      Singapore    Engineer  105000
49    Yusuf   31      Singapore   Developer   89000

In [40]:
# Drop rows where City is duplicated — keeps first unique City only
df_csv.drop_duplicates(subset="City")

       Name  Age           City Occupation  Salary
0     Alice   30       New York   Engineer   70000
1       Bob   30         London     Doctor   90000
2   Charlie   35          Paris     Artist   50000
3     David   35         Berlin    Teacher   60000
4       Eva   22          Tokyo    Student   15000
5     Frank   28         Sydney       Chef   55000
6     Grace   32  San Francisco   Designer   80000
7     Helen   27          Seoul  Scientist   75000
8       Ian   45        Toronto    Manager   95000
9     Julia   38      Singapore     Lawyer   85000
10    Kevin   30        Chicago    Analyst   65000
11    Linda   35    Los Angeles     Writer   52000

In [41]:
# Keep last occurrence instead of first
df_csv.drop_duplicates(subset="City", keep="last")

      Name  Age           City Occupation  Salary
7    Helen   27          Seoul  Scientist   75000
20     Uma   36  San Francisco   Engineer  110000
23  Xander   27        Chicago  Developer   69000
26   Aaron   25    Los Angeles    Student   14000
29   Diana   29       New York    Analyst   68000
31   Fiona   26         London    Analyst   58000
34    Ivan   23          Paris    Student   11000
37    Lena   27         Berlin    Teacher   55000
40  Oliver   28          Tokyo  Developer   74000
43    Sara   26         Sydney    Teacher   53000
46    Vera   29        Toronto    Analyst   66000
49   Yusuf   31      Singapore  Developer   89000

In [ ]:
# Practical use: get a unique list of cities
unique_cities = df_csv.drop_duplicates(subset="City")[["City"]] 
display(unique_cities)

             City
0        New York
1          London
2           Paris
3          Berlin
4           Tokyo
5          Sydney
6   San Francisco
7           Seoul
8         Toronto
9       Singapore
10        Chicago
11    Los Angeles