In [ ]:
# %pip install pandas

Requirement already satisfied: pandas in c:\users\gujin\dev\j-notebook\venv\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=2.3.3 in c:\users\gujin\dev\j-notebook\venv\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gujin\dev\j-notebook\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\gujin\dev\j-notebook\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\gujin\dev\j-notebook\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
print("✅ Ready — pandas:", pd.__version__)

✅ Ready — pandas: 3.0.0

# Inner join

An inner join returns only the rows where the key exists in both DataFrames. Rows that don't find a match in the other table are dropped entirely.

Inner join = intersection. Only rows present in both tables survive. It's the strictest join — safest when you only want complete, matched data, but you can silently lose rows if the keys don't align perfectly.

In [ ]:
df_employees = pd.read_csv('data/dummy_employees.csv')
df_reviews = pd.read_csv('data/performance_review.csv')

print("Employees total:", len(df_employees)) 
print("Reviews total:", len(df_reviews))

# inner join on Name (default how="inner")
df_inner = df_employees.merge(df_reviews, on='Name', how='inner')
display(df_inner)

# if the reviews file used "EmployeeName" instead of "Name"
# df_employees.merge(df_reviews, left_on="Name", right_on="EmployeeName", how="inner")

Employees total: 50
Reviews total: 15

,Name,Age,Sex,City,Occupation,Salary,ReviewYear,PerformanceRating,PromotionEligible
0,Alice,30,Female,New York,Engineer,70000,2024,4.5,True
1,Bob,30,Male,London,Doctor,90000,2024,3.8,False
2,Grace,32,Female,San Francisco,Designer,80000,2024,4.9,True
3,Ian,45,Male,Toronto,Manager,95000,2024,4.2,True
4,Julia,38,Female,Singapore,Lawyer,85000,2024,3.5,False
5,Mike,29,Male,New York,Developer,72000,2024,4.7,True
6,Nina,34,Female,New York,Consultant,81000,2024,4.1,True
7,Oscar,41,Male,New York,Architect,95000,2024,3.9,False
8,Quinn,33,Female,London,Engineer,85000,2024,4.6,True
9,Rachel,40,Female,London,Manager,102000,2024,4.8,True
10,Uma,36,Female,San Francisco,Engineer,110000,2024,5.0,True
11,Wendy,44,Female,Chicago,Manager,98000,2024,4.3,True
12,Bella,43,Female,New York,Doctor,120000,2024,4.0,False
13,Carlos,37,Male,New York,Lawyer,105000,2024,3.7,False
14,Xena,36,Female,Singapore,Engineer,105000,2024,4.9,True

# Left join

A left join keeps all rows from the left DataFrame, and brings in matching data from the right. Where there's no match, the right-side columns are filled with NaN.

Left join = "Give me everything from the left table, and attach whatever you can find from the right." The left table is always fully preserved — it's the safest default when you're enriching a primary dataset with supplementary data.

In [8]:
df_left = df_employees.merge(df_reviews, on='Name', how='left')
display(df_left)

,Name,Age,Sex,City,Occupation,Salary,ReviewYear,PerformanceRating,PromotionEligible
0,Alice,30,Female,New York,Engineer,70000,2024.0,4.5,True
1,Bob,30,Male,London,Doctor,90000,2024.0,3.8,False
2,Charlie,35,Male,Paris,Artist,50000,NaN,NaN,NaN
3,David,35,Male,Berlin,Teacher,60000,NaN,NaN,NaN
4,Eva,22,Female,Tokyo,Student,15000,NaN,NaN,NaN
5,Frank,28,Male,Sydney,Chef,55000,NaN,NaN,NaN
6,Grace,32,Female,San Francisco,Designer,80000,2024.0,4.9,True
7,Helen,27,Female,Seoul,Scientist,75000,NaN,NaN,NaN
8,Ian,45,Male,Toronto,Manager,95000,2024.0,4.2,True
9,Julia,38,Female,Singapore,Lawyer,85000,2024.0,3.5,False
10,Kevin,30,Male,Chicago,Analyst,65000,NaN,NaN,NaN
11,Linda,35,Female,Los Angeles,Writer,52000,NaN,NaN,NaN
12,Mike,29,Male,New York,Developer,72000,2024.0,4.7,True
13,Nina,34,Female,New York,Consultant,81000,2024.0,4.1,True
14,Oscar,41,Male,New York,Architect,95000,2024.0,3.9,False
15,Paul,26,Male,London,Student,12000,NaN,NaN,NaN
16,Quinn,33,Female,London,Engineer,85000,2024.0,4.6,True
17,Rachel,40,Female,London,Manager,102000,2024.0,4.8,True
18,Sam,28,Male,San Francisco,Developer,95000,NaN,NaN,NaN
19,Tina,31,Female,San Francisco,Designer,88000,NaN,NaN,NaN
20,Uma,36,Female,San Francisco,Engineer,110000,2024.0,5.0,True
21,Victor,29,Male,Chicago,Analyst,67000,NaN,NaN,NaN
22,Wendy,44,Female,Chicago,Manager,98000,2024.0,4.3,True
23,Xander,27,Male,Chicago,Developer,69000,NaN,NaN,NaN
24,Yara,32,Female,Los Angeles,Designer,76000,NaN,NaN,NaN
25,Zoe,38,Female,Los Angeles,Lawyer,91000,NaN,NaN,NaN
26,Aaron,25,Male,Los Angeles,Student,14000,NaN,NaN,NaN
27,Bella,43,Female,New York,Doctor,120000,2024.0,4.0,False
28,Carlos,37,Male,New York,Lawyer,105000,2024.0,3.7,False
29,Diana,29,Female,New York,Analyst,68000,NaN,NaN,NaN
30,Ethan,34,Male,London,Doctor,98000,NaN,NaN,NaN
31,Fiona,26,Female,London,Analyst,58000,NaN,NaN,NaN
32,George,48,Male,Paris,Architect,82000,NaN,NaN,NaN
33,Hannah,31,Female,Paris,Designer,65000,NaN,NaN,NaN
34,Ivan,23,Male,Paris,Student,11000,NaN,NaN,NaN
35,Jade,39,Female,Berlin,Engineer,78000,NaN,NaN,NaN
36,Karl,33,Male,Berlin,Doctor,94000,NaN,NaN,NaN
37,Lena,27,Female,Berlin,Teacher,55000,NaN,NaN,NaN
38,Marco,45,Male,Tokyo,Manager,88000,NaN,NaN,NaN
39,Nora,30,Female,Tokyo,Engineer,79000,NaN,NaN,NaN
40,Oliver,28,Male,Tokyo,Developer,74000,NaN,NaN,NaN
41,Priya,35,Female,Sydney,Scientist,81000,NaN,NaN,NaN
42,Rick,41,Male,Sydney,Doctor,99000,NaN,NaN,NaN
43,Sara,26,Female,Sydney,Teacher,53000,NaN,NaN,NaN
44,Tom,38,Male,Toronto,Lawyer,97000,NaN,NaN,NaN
45,Ursula,32,Female,Toronto,Engineer,84000,NaN,NaN,NaN
46,Vera,29,Female,Toronto,Analyst,66000,NaN,NaN,NaN
47,Will,44,Male,Singapore,Manager,115000,NaN,NaN,NaN
48,Xena,36,Female,Singapore,Engineer,105000,2024.0,4.9,True
49,Yusuf,31,Male,Singapore,Developer,89000,NaN,NaN,NaN

In [9]:
# Practical: flag who is eligible for promotion (False for unreviewed)
df_left["PromotionEligible"] = df_left["PromotionEligible"].fillna(False)
display(df_left[["Name", "Salary", "PerformanceRating", "PromotionEligible"]])

       Name  Salary  PerformanceRating PromotionEligible
0     Alice   70000                4.5              True
1       Bob   90000                3.8             False
2   Charlie   50000                NaN             False
3     David   60000                NaN             False
4       Eva   15000                NaN             False
5     Frank   55000                NaN             False
6     Grace   80000                4.9              True
7     Helen   75000                NaN             False
8       Ian   95000                4.2              True
9     Julia   85000                3.5             False
10    Kevin   65000                NaN             False
11    Linda   52000                NaN             False
12     Mike   72000                4.7              True
13     Nina   81000                4.1              True
14    Oscar   95000                3.9             False
15     Paul   12000                NaN             False
16    Quinn   85000                4.6              True
17   Rachel  102000                4.8              True
18      Sam   95000                NaN             False
19     Tina   88000                NaN             False
20      Uma  110000                5.0              True
21   Victor   67000                NaN             False
22    Wendy   98000                4.3              True
23   Xander   69000                NaN             False
24     Yara   76000                NaN             False
25      Zoe   91000                NaN             False
26    Aaron   14000                NaN             False
27    Bella  120000                4.0             False
28   Carlos  105000                3.7             False
29    Diana   68000                NaN             False
30    Ethan   98000                NaN             False
31    Fiona   58000                NaN             False
32   George   82000                NaN             False
33   Hannah   65000                NaN             False
34     Ivan   11000                NaN             False
35     Jade   78000                NaN             False
36     Karl   94000                NaN             False
37     Lena   55000                NaN             False
38    Marco   88000                NaN             False
39     Nora   79000                NaN             False
40   Oliver   74000                NaN             False
41    Priya   81000                NaN             False
42     Rick   99000                NaN             False
43     Sara   53000                NaN             False
44      Tom   97000                NaN             False
45   Ursula   84000                NaN             False
46     Vera   66000                NaN             False
47     Will  115000                NaN             False
48     Xena  105000                4.9              True
49    Yusuf   89000                NaN             False

Right join — rarely used in practice. Anything a right join does can be rewritten as a left join by swapping the order of the DataFrames.

Outer join — used, but less commonly than inner/left. It's the most permissive join — keeps all rows from both sides, with NaN wherever there's no match.